### PR TITLE
Feature/commit validation

### PR DESCRIPTION
**Pull request by ehcorrea**
Add tools to assist with files and commits patterns.

Used libs:
[cz-cli](https://github.com/commitizen/cz-cli)
[husky](https://github.com/typicode/husky)
[commitlint](https://github.com/conventional-changelog/commitlint)
[lint-staged](https://github.com/okonet/lint-staged)

### How to use

1. Add files to Staged Changes 

2. Run the command `git commit`(without -m) and wait for the lint staged command to finish, this will validate that your files are written according to eslint rules 

3. Error case exemple. The commit process will stop until there are no warnings/errors 
2.5 - caso seja encontrado algum erro nos arquivos
4. Select the type of change, you can see with more details in **changelog.config.json** 

5. Describe your commit based on the questions, not all are required 

6. Final output exemple

7. Git exemple, you can se more details  [here](https://github.com/Br-Dev-Streamers/brdevstreamers-ui/pull/46/commits)

### CODE REVIEW

**Comment by nandosangenetto** [comment]
Could you please add instructions in our README.md file?

**Comment by ehcorrea** [comment]
> Could you please add instructions in our README.md file?

@nandosangenetto 
Would you like a simplified version with only written instructions or with images?

**Comment by nandosangenetto** [comment]
> > Could you please add instructions in our README.md file?
> 
> @nandosangenetto Would you like a simplified version with only written instructions or with images?

Simplified version is enough :)

**Comment by ehcorrea** [comment]
@nandosangenetto done 👍🏾

**Review by nandosangenetto — APPROVED** [review]

**Comment by nandosangenetto** [comment]
Well done

**Pull request merged**
