### PR TITLE
feat(plop): added plop file to automatic generate component files

### PR DESCRIPTION
**Pull request by ehcorrea**
How to use:
Run the command yarn generate ComponentName
Write the folder inside component folder

Result:
A file will be created in the  folder inside component folder, with initial structures already defined:
ComponentName.tsx

Road Map:
In the future, new templates can be added, such as styles, tests and stories.

Used libs:
[plop](https://github.com/plopjs/plop)

### CODE REVIEW

**Comment by nandosangenetto** [comment]
What is your proposal for adding this tool?

**Comment by ehcorrea** [comment]
> What is your proposal for adding this tool?

You can generate componet files with a single comand, based on templates. My idea was to have more templates, but I saw that they removed the test files. You can forcing an initial pattern and complementing with the prettier. For exemple, with command `generate Button`, you could have three files created: 

1. The component file(Button.tsx) with the initial structure(including imports):
  ```
   import {ButtonProps} fom './types'
   import "./Button.css";
   const Button = ({childrens, ...props}: ButtonProps) => <button ...props>{childrens}</button>
   export default Button
```
   
 2. The styles file with the initial structure:
  ```
 .button{
    height: 20px;
    max-width: 50px;
    width: 100%;
  } 
```
3. The test file with the initial structure:
```
import { screen, render } from '@testing-library/react';
import Button from './'

describe('<Button />', () => {
  it('should render the medium size by default', () => {
    render (<Button>lorem ipsum</Button>);
    expect(screen.getByRole('button', { name: /lorem ipsum/i })).tobeInTheDocument();
  });
});
```

**Comment by flaviojmendes** [comment]
Agree, think we can hold this one for now. Then, if we feel the need on creating a larger amount of new components we put this in our radar again.  @ehcorrea is that okay?

**Comment by ehcorrea** [comment]
> Agree, think we can hold this one for now. Then, if we feel the need on creating a larger amount of new components we put this in our radar again. @ehcorrea is that okay?

Nice. Thats all right, its a simple modification to do;

**Pull request closed without merging**
