### PR TITLE
Feature/raid button

### LINKED ISSUE #24: Create button to copy a command to raid channels
Create a button or link inside the streamer card to copy a command to raid it

### PR DESCRIPTION
**Pull request by joaom00**
This PR adds raid button to copy raid command to clipboard.

# Demo

https://user-images.githubusercontent.com/48808846/158694797-e927c571-cca5-40ec-94a7-7b0b6fd3e4a6.mp4

Closes #24

### CODE REVIEW

**Comment by nandosangenetto** [comment]
image

The button is too close to the text. Do you think it is possible to increase the space between them?

**Comment by nandosangenetto** [comment]
Adding @brunobandev as a reviewer to check this design change.

Btw, it is a nice feature. That is going to be useful.


Ps: Make sure to fix the test :D

**Comment by joaom00** [comment]
The test is passing for me. I don't know what could have happened to have failed.

**Review by brunobandev — APPROVED** [review]
@joaom00 well done, it'll be very useful mainly for other streamers.

**Comment by joaom00** [comment]
Thanks! @brunobandev

**Comment by nandosangenetto** [comment]
> The test is passing on my machine. I don't know what could have happened to have failed.

I'm going to try here tomorrow.

**Comment by nandosangenetto** [comment]
@joaom00 It is a flaky test. It will work most of the time testing using the Cypress' graphic interface (`yarn open`) but it will always fail when using the CLI (`yarn cy:run`).

I could find some workarounds, take a look:
- https://stackoverflow.com/questions/56306153/domexception-on-calling-navigator-clipboard-readtext
- https://github.com/cypress-io/cypress/issues/18198
- https://github.com/cypress-io/cypress/issues/9105

**Comment by nandosangenetto** [comment]
Also, I was thinking here.

The raid button is not something that most users will use. It is going to be used by streamers. It would be nice if the user could set the website as "streamer mode." It could be a toggle button.

**Comment by joaom00** [comment]
@nandosangenetto All tests are passing!!

**Comment by joaom00** [comment]
> Also, I was thinking here.
> 
> The raid button is not something that most users will use. It is going to be used by streamers. It would be nice if the user could set the website as "streamer mode." It could be a toggle button.


Would it make sense to do this just for the raid button? I think it would make sense if we had more features for streamers. This would fit in with what @brunobandev suggested #23

**Review by nandosangenetto — APPROVED** [review]

**Comment by nandosangenetto** [comment]
> > Also, I was thinking here.
> > The raid button is not something that most users will use. It is going to be used by streamers. It would be nice if the user could set the website as "streamer mode." It could be a toggle button.
> 
> Would it make sense to do this just for the raid button? I think it would make sense if we had more features for streamers. This would fit in with what @brunobandev suggested #23

Yeah, we can discuss about that later.

**Pull request merged**
